src/main/java/org/sgy/mall/model/Page.java
package org.sgy.mall.model;

public class Page {
	private int page;
	private int limit;
	private int total;

	public int getStartIndex() {
		int index = (page - 1) * limit;
		return index;
	}

	public int getEndIndex() {
		int index = page * limit - 1;
		return index;
	}

	public int getPage() {
		return page;
	}

	public void setPage(int page) {
		this.page = page;
	}

	public int getLimit() {
		return limit;
	}

	public void setLimit(int limit) {
		this.limit = limit;
	}

	public int getTotal() {
		return total;
	}

	public void setTotal(int total) {
		this.total = total;
	}

}

src/main/java/org/sgy/mall/model/Product.java
package org.sgy.mall.model;

public class Product {
	private int id;
	private String name;
	private String brand;
	private Integer price;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getBrand() {
		return brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public Integer getPrice() {
		return price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

}

src/main/java/org/sgy/mall/servlet/ProductServlet.java
package org.sgy.mall.servlet;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.sgy.mall.dao.impl.ProductDaoImpl;
import org.sgy.mall.model.Product;

public class ProductServlet extends HttpServlet {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public ProductServlet() {
	}

	@Override
	public void init() throws ServletException {
	}

	@Override
	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		// 从数据库中取出商品列表
		ProductDaoImpl productDao = new ProductDaoImpl();
		List<Product> list = productDao.fetchList();
		// 将数据传输到jsp
		request.setAttribute("list", list);
		request.getRequestDispatcher("/product/productList.jsp").forward(request, response);
	}

	@Override
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws IOException {
		String action = request.getParameter("action");
		if (action.equals("add")) {
			add(request, response);
		}
	}

	private void add(HttpServletRequest request, HttpServletResponse response) throws IOException {
		// 获取参数
		String name = request.getParameter("name");
		String brand = request.getParameter("brand");
		String priceStr = request.getParameter("price");
		int price = 0;
		try {
			price = Integer.parseInt(priceStr);
		} catch (Exception e) {
		}

		// 构建javabean
		Product product = new Product();
		product.setName(name);
		product.setBrand(brand);
		product.setPrice(price);

		// 调用dao
		ProductDaoImpl productDao = new ProductDaoImpl();
		boolean success = productDao.add(product);
		if (success) {
			response.getWriter().println("add product success");
		}
	}

	private void update(HttpServletRequest request, HttpServletResponse response) {

	}
}

src/main/webapp/product/cartList.jsp
<%@page import="org.sgy.mall.model.Cart"%>
<%@page import="java.text.SimpleDateFormat"%>
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%
	String path = request.getContextPath();
	String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort()
			+ path + "/";
%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<base href="<%=basePath%>">
<title></title>
</head>
<body>
	<form action="orderServlet?type=add" method="post">
		<table border=1>
			<tr>
				<th>id</th>
				<th>name</th>
				<th>price</th>
				<th>num</th>
				<th>total</th>
			</tr>

			<%
				//获取购物车数据
				Object object = session.getAttribute("cartList");
				List<Cart> cartList = new ArrayList();
				if (object != null) {
					cartList = (ArrayList<Cart>) object;
				}

				//计算购物车总价
				double sum = 0.0;

				for (Cart cart : cartList) {
			%>
			<tr>
				<td><input value=<%=cart.getId()%> name="productId"></td>
				<td><input value=<%=cart.getName()%> name="productName"></td>
				<td><input value=<%=cart.getPrice()%> name="price"></td>
				<td><input value=<%=cart.getNum()%> name="num"></td>
				<td><%=cart.getPrice() * cart.getNum()%></td>
			</tr>
			<%
				sum += cart.getPrice() * cart.getNum();
				}
			%>

			<tr>
				<td>总价:<%=sum%></td>
			</tr>
		</table>
		<input type="submit" value="提交订单">
	</form>
	<br>
</body>
</html>

src/main/webapp/product/orderList.jsp
<%@page import="org.sgy.mall.model.OrderInfo"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@page import="java.text.SimpleDateFormat"%>
<%@taglib prefix="myTag" uri="http://localhost/tags/myTags"%>
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%
	String path = request.getContextPath();
	String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort()
			+ path + "/";
%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<base href="<%=basePath%>">
<title></title>
</head>
<body>


	<table border="1">
		<tr>
			<th>id</th>
			<th>username</th>
			<th>address</th>
			<th>orderTime</th>
		</tr>
		<c:forEach var="order" items="${list}" begin="${page.startIndex}" end="${page.endIndex}">
			<tr>
				<td>${order.id}</td>
				<td><${order.username}</td>
				<td>${order.address }</td>
				<td>${order.orderTime }</td>
			</tr>
		</c:forEach>
		<myTag:page page="${page}"></myTag:page>
	</table>
	<br>
</body>
</html>

src/main/webapp/product/productAdd.jsp
<%@page import="java.text.SimpleDateFormat"%>
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%
	String path = request.getContextPath();
	String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort()
			+ path + "/";
%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<base href="<%=basePath%>">
<title></title>
</head>
<body>

	<form method="post" action="./productServlet?action=add">

		商品名称<input name="name">
		<br>
                     品牌<input name="brand">
                     <br>
                     价格<input name="price">
                     <br>
       <input type="submit" value="添加商品">
	</form>

</body>
</html>

src/main/webapp/product/productList.jsp
<%@page import="org.sgy.mall.model.Product"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@page import="org.sgy.mall.dao.impl.ProductDaoImpl"%>
<%@page import="java.text.SimpleDateFormat"%>
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%
	String path = request.getContextPath();
	String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort()
			+ path + "/";
%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<base href="<%=basePath%>">
<title></title>
</head>
<body>

	<c:forEach items="${list}" var="vo">
		<form method="post" action="/edmall/CartServlet?type=add">
			<h1>产品1</h1>
			<ul>
				<li>id:${vo.id}</li>
				<li>商品名称：${vo.name}</li>
				<li>品牌：${vo.brand}</li>
				<li>价格:${vo.price}</li>
			</ul>
			<input type="hidden" name="id" value=${vo.id}> <input
				type="hidden" name="name" value=${vo.name}> <input
				type="hidden" name="brand" value=${vo.brand}> <input
				type="hidden" name="price" value=${vo.price}> 购买数量:<input
				name="num"> <input type="submit" value="添加到购物车">
		</form>
	</c:forEach>
</body>
</html>

src/main/webapp/product/productList1.jsp
<%@page import="org.sgy.mall.model.Product"%>
<%@page import="org.sgy.mall.dao.impl.ProductDaoImpl"%>
<%@page import="java.text.SimpleDateFormat"%>
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%
	String path = request.getContextPath();
	String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort()
			+ path + "/";
%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<base href="<%=basePath%>">
<title></title>
</head>
<body>


	<%
	    Object listObj=request.getAttribute("list");
	    if(listObj==null){
	    	return;
	    }
	    List<Product> productList=(List<Product>) listObj;
		for (Product product : productList) {
	%>
	<form method="post" action="/edmall/CartServlet?type=add">
		<h1>产品1</h1>
		<ul>
			<li>id:<%=product.getId()%></li>
			<li>商品名称：<%=product.getName()%></li>
			<li>品牌：<%=product.getBrand()%></li>
			<li>价格:<%=product.getPrice()%></li>
		</ul>
		<input type="hidden" name="id" value=<%=product.getId()%>> <input
			type="hidden" name="name" value=<%=product.getName()%>> <input
			type="hidden" name="brand" value=<%=product.getBrand()%>> <input
			type="hidden" name="price" value=<%=product.getPrice()%>>
		购买数量:<input name="num"> <input type="submit" value="添加到购物车">
	</form>
	<%
		}
	%>

</body>
</html>

src/main/webapp/product/productUpAndDown.jsp
<%@page import="java.text.SimpleDateFormat" %>
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8" %>
<%
    String path = request.getContextPath();
    String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort()
            + path + "/";
%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
    <base href="<%=basePath%>">
    <title></title>
</head>
<body>

<br>
</body>
</html>

src/main/webapp/product/statOrder.jsp
<%@page import="java.text.SimpleDateFormat" %>
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8" %>
<%
    String path = request.getContextPath();
    String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort()
            + path + "/";
%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
    <base href="<%=basePath%>">
    <title></title>
</head>
<body>
<div align="center">
<%
String filename=request.getParameter("filename");
if(filename!=null&&filename.length()>0){
	String graphUrl=request.getContextPath()+"/DisplayChart?filename="+filename;

%>
<img alt="" src="<%=graphUrl%>" height=300 width=500>
<%
}
%>
</div>
<br>
</body>
</html>